server:
    port: 8080
    http2:
        enabled: true
    error:
        whitelabel:
            enabled: false
spring:
    application:
        name: spring-ai
    main:
        web-application-type: reactive
    webflux:
        base-path: /
    servlet:
        multipart:
            max-file-size: ${MAX_FILE_SIZE:-1}
            max-request-size: ${MAX_REQUEST_SIZE:-1}
            enabled: true
    codec:
        max-in-memory-size: 64MB
    jackson:
        default-property-inclusion: non_null

    data:
        redis:
            host: ${REDIS_HOST_NAME:localhost}
            port: 6379
    session:
        store-type: redis
        redis:
            namespace: spring:ses
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:5432/${POSTGRES_DB_NAME:ragdb}
        username: ${POSTGRES_USERNAME:postgres}
        password: ${POSTGRES_PASSWORD:postgres}
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
        show-sql: false
    flyway:
        enabled: true
        baseline-on-migrate: false
        clean-disabled: true
        locations: classpath:db/migration
    sql:
        init:
            mode: never
    web:
        resources:
            add-mappings: false
    # phi3:mini owl/t-lite gemma3:1b-it-qat
    # qwen2.5:0.5b qwen3:0.6b
    ai:
        openai:
            base-url: http://${OLLAMA_HOSTNAME:localhost}:11434
            api-key: dummy # обязателен (любая непустая строка)
            chat:
                options:
                    model: qwen2.5:7b-instruct
        ollama:
            base-url: http://${OLLAMA_HOSTNAME:localhost}:11434
            embedding:
                model: ${OLLAMA_EMBEDDING_MODEL:nomic-embed-text}
                options:
                    num-ctx: 8192
            # чтобы не плодить лишний ChatModel (и не уехать в /api/chat):
            chat:
                enabled: false
        chat:
            memory:
                enabled: false

mybatis:
    mapper-locations: classpath*:db/mybatis/*.xml
    type-handlers-package: classpath*:mcdodik.springai.db.mybatis.handler

logging:
    level:
        root: INFO
        mcdodik: DEBUG
        #        org.flywaydb: DEBUG

        # WebClient + Reactor Netty
        #  reactor.netty.http.client: DEBUG
        #  reactor.netty.transport: DEBUG
        #  reactor.netty.resources: DEBUG

        # Spring WebFlux
        org.springframework.web: DEBUG
        org.springframework.web.reactive: DEBUG
        org.springframework.http.client: DEBUG
        org.springframework.web.client.RestTemplate: DEBUG

        # Чтобы видеть фильтры и обмен данными
#        org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
#        org.springframework.web.reactive.function.client.ExchangeFilterFunctions: TRACE

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            probes:
                enabled: true
    tracing:
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://${ZIPKIN_URL:localhost}:9411/api/v2/spans

app:
    security:
        enabled: false
        required-scope: ""
mcdodik:
    openrouter:
        enabled: true
        temperature: 0.2
        max-tokens: 8192
        top-p: 0.95
        api-key: ${OPENROUTER_API_KEY}
        models:
            default: ${OPEN_ROUTER_MODEL_DEFAULT:qwen/qwen3-next-80b-a3b-instruct}
            summary: ${OPEN_ROUTER_MODEL_SUMMARY:qwen/qwen3-next-80b-a3b-instruct}
            promptGen: ${OPEN_ROUTER_MODEL_PROMPT_GEN:qwen/qwen3-next-80b-a3b-instruct}
            chunking: ${OPEN_ROUTER_MODEL_CHUNKING:qwen/qwen3-next-80b-a3b-instruct}
    advisors:
        vector:
            topK: 24
            vectorStoreSimilarityThreshold: 0.35
            rerankSimilarityThreshold: 0.75
            finalK: 12
            maxContextTokens: 20000
            order: 0
    chunks:
        dedup:
            recompute-batchSize: 2000
            page-size: 2000
            top-terms-per-doc: 15
            candidate-limit: 500
            similarity-threshold: 0.9

    telegram:
        token: ${TELEGRAM_BOT_TOKEN}
        channels: ${TELEGRAM_CHANNELS}
