spring:
  application:
    name: spring-ai
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true
  web:
    resources:
      add-mappings: false

  ai:
    chat:
      advisors:
        - bean: simpleLoggerAdvisor
    ollama:
      embedding:
        model: nomic-embed-text
        options:
          num-ctx: 8192
      base-url: http://localhost:11434
      chat:
        options:
          model: tinyllama
          temperature: 0.7
    vectorstore:
      pgvector:
        initialize-schema: true

openrouter:
  api-key: ХУЙ СОСИ

logging:
  level:
    sql: debug
    web: debug
