package mcdodik.springai.config.datasource

import mcdodik.springai.config.Loggable
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.Statement

class ProxyConnection(
    private val delegate: Connection,
) : Connection by delegate,
    Loggable {
    override fun createStatement(): Statement = ProxyStatement(delegate.createStatement(), delegate)

    override fun prepareStatement(sql: String): PreparedStatement = ProxyPreparedStatement(delegate.prepareStatement(sql), delegate, sql, logger)

    override fun prepareStatement(
        sql: String,
        autoGeneratedKeys: Int,
    ): PreparedStatement = ProxyPreparedStatement(delegate.prepareStatement(sql, autoGeneratedKeys), delegate, sql, logger)

    override fun prepareStatement(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
    ): PreparedStatement = ProxyPreparedStatement(delegate.prepareStatement(sql, resultSetType, resultSetConcurrency), delegate, sql, logger)

    override fun prepareStatement(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int,
    ): PreparedStatement =
        ProxyPreparedStatement(
            delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability),
            delegate,
            sql,
            logger,
        )
}
