package mcdodik.springai.db.entity.rag

import java.time.LocalDateTime
import java.util.UUID
import mcdodik.springai.extensions.sha256
import org.springframework.web.multipart.MultipartFile

/**
 * Data class representing information about a document stored in the system.
 *
 * This class holds metadata such as unique ID, file name, content type, hash, number of chunks,
 * creation timestamp, and an optional summary. It is used to store and manage document records in the database.
 */
data class DocumentInfo(
    /**
     * Unique identifier for the document. Automatically generated using UUID.randomUUID() if not provided.
     */
    val id: UUID = UUID.randomUUID(),

    /**
     * Name of the original file associated with the document.
     */
    val fileName: String,

    /**
     * MIME type or extension of the file (e.g., "text/plain", "application/pdf").
     */
    val extension: String,

    /**
     * SHA-256 hash of the file's content, used to identify duplicates or unchanged files.
     */
    val hash: String,

    /**
     * Number of text chunks the document was split into during processing.
     */
    val chunkCount: Integer,

    /**
     * Timestamp when the document was created or added to the system.
     */
    val createdAt: LocalDateTime,

    /**
     * Optional summary of the document's content, typically generated by an AI model.
     */
    val summary: String?
) {
    /**
     * Companion object providing factory methods for creating instances of [DocumentInfo].
     */
    companion object {
        /**
         * Creates a new [DocumentInfo] instance based on a [MultipartFile] and chunk count.
         *
         * @param file The uploaded file from which metadata will be extracted.
         * @param chunkCount The number of text chunks the file was split into.
         * @param summary Optional summary of the document (default is "empty").
         * @return A new [DocumentInfo] object with the specified properties.
         */
        fun createFromFileAndCunks(
            file: MultipartFile,
            chunkCount: Int,
            summary: String = "empty"
        ): DocumentInfo {
            return DocumentInfo(
                fileName = file.originalFilename.toString(),
                extension = file.contentType.toString(),
                hash = file.sha256(),
                chunkCount = chunkCount as Integer,
                createdAt = LocalDateTime.now(),
                summary = summary
            )
        }
    }
}
