name: CI

on:
    pull_request:
        branches: [ "main" ]
    push:
        branches: [ "feature/**", "fix/**", "hotfix/**" ]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            checks: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: "21"
            - uses: gradle/actions/setup-gradle@v3
            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v2

            - name: chmod-geadle
              run: chmod +x ./gradlew

            - name: Ktlint
              run: ./gradlew ktlintCheck --no-daemon
            - name: Detekt
              run: ./gradlew detekt --no-daemon

            - name: Build
              run: ./gradlew build -x test --no-daemon

            - name: Test
              run: ./gradlew test --no-daemon
